name: RSpec

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      CI: true
      ALLOW_FAILURES: "${{ matrix.allow_failures }}"
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.7, "3.0", 3.1, 3.2]

        gemfile: [
          "gemfiles/rails_5_2.gemfile",
          "gemfiles/rails_6_0.gemfile",
          "gemfiles/rails_6_2.gemfile",
          "gemfiles/rails_7_0.gemfile"
        ]

        allow_failures:
          - false

        exclude:
          - ruby: 2.4
            gemfile: gemfiles/rails_6_0.gemfile
          - ruby: 2.4
            gemfile: gemfiles/rails_6_2.gemfile
          - ruby: 2.4
            gemfile: gemfiles/rails_7_0.gemfile
          - ruby: 2.4
            gemfile: gemfiles/railsmaster.gemfile

        include:
          - ruby: ruby-head
            gemfile: gemfiles/railsmaster.gemfile
            allow_failures: true

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: 4
        bundler: 2.2.0
    - name: Run RSpec
      run: bundle exec rake spec || $ALLOW_FAILURES
